### ISSUE TITLE
Permission problem for /home/archie/aur

### ISSUE THREAD

**Issue by pozar87** [marcopompili/docker-archlinux-makepkg#1]
Hello,

I just create new test vm with `tester-make.sh` (process finished without errors).
Next I tried to run some build test:

> ./tester.sh ~/src/arch-pkg/python-sphinxcontrib-autoprogram          
> making python-sphinxcontrib-autoprogram
> Installing dependencies:  None
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community                                   3.6 MiB  1580K/s 00:02 [######################################] 100%
> error: target not found: None
> ==> ERROR: You do not have write permission to create packages in /home/archie/aur.
>     Aborting...
> Removing VM: python-sphinxcontrib-autoprogram

This is odd - this line form `tester-make.sh`:

> arch-chroot $ROOTFS /bin/sh -c 'chown archie.archie /home/archie/aur'

Looks ok to me ...
Do you have any idea what am I doing wrong?

PS Nice idea with this project - I was trying to do the same thing and just found you :)

**Comment by marcopompili** [comment]
Hey

I guess you don't have the rights to access the folder python-sphinxcontrib-autoprogram ? Like that folder is owned by "root" or something like that.

Anyway looks like the script cannot tests python packages because yaourt won't find "python2" or "python"  as a dependency, because of the functions used for setting required deps on both py2 and py3.

**Comment by pozar87** [comment]
Hello,
Thanks for answer!
I double checked the permissions and they looks OK. I also tried relative/absolute paths - no result :( Should I try to re-generate docker image form parent directory of my local folder with PKGBUILDs? 
Perhaps docker need to have it that way to be able to copy/add it to image?


About missing dependencies - you are right  but this seems a generic problem for **makepkg** - the build tools doesn't check the dependencies overrides while building whole packages form PKGBUILD (but this works if you install  selected sub-package directly from AUR) I'm going to drill this a bit more :)

**Comment by marcopompili** [comment]
I'm switching to a chroot environment instead of docker, instead of using docker i'll be using a script that uses a clean chroot, arch linux has plenty of tools for that. I guess when I got my script stable I'll publish a script on aur.

In the meantime i give you some references: https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot

I'll delete this repo soon.

**Comment by pozar87** [comment]
Alright! The `chroot` way seems very promising - thanks for pointing that out, and good luck with your script.
Regards,
